APPS_BASE_PATH = "/Users/harikishenh/Dev/Main_Project/"
BENIGN_PATH = APPS_BASE_PATH + "Benign/"
MALWARE_PATH = APPS_BASE_PATH + "Malware/"
DEST_PATH = APPS_BASE_PATH + "Temp/"
BASE_PATH = APPS_BASE_PATH + "Android-Malware-Detector"  # Location of scripts
DEX2SMALI_PATH = BASE_PATH + '/tools/'
SCRIPT_PATH = BASE_PATH + '/scripts/'
FILES_PATH = BASE_PATH + '/files/'
INTEGRATED_PATH = BASE_PATH + '/artemis'
VECTOR_STORE = APPS_BASE_PATH + "xdata.txt"
LABEL_STORE = APPS_BASE_PATH + "ydata.txt"
MODEL_STORE = APPS_BASE_PATH
TEST_DATA_LOCATION = APPS_BASE_PATH + "Test/"
