APPS_BASE_PATH = "/home/ubuntu/utils/"
BENIGN_PATH = APPS_BASE_PATH + "Benign/"
MALWARE_PATH = APPS_BASE_PATH + "Malware/"
DEST_PATH = APPS_BASE_PATH + "Temp/"
BASE_PATH = "/home/ubuntu/A.R.T.E.M.I.S"  # Location of scripts
DEX2SMALI_PATH = BASE_PATH + '/tools/'
SCRIPT_PATH = BASE_PATH + '/scripts/'
FILES_PATH = BASE_PATH + '/files/'
INTEGRATED_PATH = BASE_PATH + '/artemis'
VECTOR_STORE = BASE_PATH + "data/xdata.txt"
LABEL_STORE = BASE_PATH + "data/ydata.txt"
MODEL_STORE = BASE_PATH + "data/"
TEST_DATA_LOCATION = APPS_BASE_PATH + "Test/"
