SEPARATOR = ";"
LANG = "en_US"  # can be en_US, fr_FR, ...
ANDROID_ID = '3F878D1CF1491B75'  # "xxxxxxxxxxxxxxxx"
GOOGLE_LOGIN = 'hari751995@gmail.com'  # "username@gmail.com"
GOOGLE_PASSWORD = 'turbodrivetopulsar1234'
AUTH_TOKEN = None  # "yyyyyyyyy"
DOWNLOAD_PATH = '/Users/harikishenh/Dev/main_project/Apps/Benign/'
SUB_CATEGORY = 'apps_topselling_new_free'
NUMBER = '10'
