path="/media/john/1561CFF65058AE0D/Test/"    #Location of Benign Apps for learning (Name should be Benign)
malpath="/media/john/1561CFF65058AE0D/Malwar/"                     # Loaction of Malware Input (APKS allowed)      
destinationPath="/home/john/AMD/restapk/"      # Location to extract to and creation of permissions list    
basePath="/home/john/AMD/Android-Malware-Detector"   #Location of scripts
DEX2SMALI_PATH = '/home/john/AMD/Android-Malware-Detector/tools/'
SCRIPT_PATH ='/home/john/AMD/Android-Malware-Detector/scripts'
INTEGRATED_PATH = '/home/john/AMD/Android-Malware-Detector/Integrated'
vectorstore = "/home/john/AMD/zdata.txt"  # data for training will be copied here...just in case...
labelstore = "/home/john/AMD/zlabel.txt"
modelstore = "/home/john/AMD/"
#APP_FOLDER="/home/john/AMD/apk/"